name: dml
channels:
- defaults
- pytorch
dependencies:
- python=3.7
- pip
- numpy
- jupyter
- matplotlib
- scikit-learn
- scipy
- pandas
- seaborn
- nltk
- h5py
- spacy
- unidecode
- pywin32
- pytorch=1.2.0
- torchvision=0.4.0
- cudatoolkit=10.0
- pip:
  - future
  - tb-nightly
  - gym
  - pillow
  - kaggle
  - ipywidgets
